[package]
name = "kube-derive"
description = "Custom derives for the kube kubernetes crates"
version = "0.43.0"
authors = ["clux <sszynrae@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/clux/kube-rs"
readme = "../README.md"

[dependencies]
proc-macro2 = "1.0.19"
quote = "1.0.7"
syn = { version = "1.0.30", features = ["extra-traits"] }
Inflector = "0.11.4"
serde_json = "1.0.53"

[lib]
proc-macro = true

[dev-dependencies]
serde = { version = "1.0.111", features = ["derive"] }
serde_yaml = "0.8.12"
k8s-openapi = { version = "0.10.0", default-features = false, features = ["v1_18"] }
